### PR TITLE
SuperBuilder: consider lombok.builder.className for builder extends clause

### LINKED ISSUE #2647: [BUG] `lombok.builder.className=Builder` breaks SuperBuilder
**Describe the bug**
When building project with SuperBuilder classes and `lombok.builder.className=Builder` in config, I get compilation issues:
```
[ERROR] /home/jbrazdil/rht/pnc-api/src/main/java/org/jboss/pnc/api/deliverablesanalyzer/dto/MavenArtifact.java:[38,1] cannot find symbol
[ERROR]   symbol:   class ArtifactBuilder
[ERROR]   location: class org.jboss.pnc.api.deliverablesanalyzer.dto.Artifact
```

**To Reproduce**
```java
@Data
@SuperBuilder
@Jacksonized
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        property = "type",
        defaultImpl = Artifact.class)
@JsonSubTypes({ @JsonSubTypes.Type(value = MavenArtifact.class, name = "MAVEN") })
public class Artifact {

    @NotNull
    public final String artifactType;

    @NotBlank
    public final String filename;

    public final long size;

    @Pattern(regexp = "^[a-f0-9]{32}$")
    public final String md5;

    @Pattern(regexp = "^[a-f0-9]{40}$")
    public final String sha1;

    @Pattern(regexp = "^[a-f0-9]{64}$")
    public final String sha256;

}
```
```
@Data
@SuperBuilder
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
@Jacksonized
public class MavenArtifact extends Artifact {

    @NotBlank
    private final String groupId;

    @NotBlank
    private final String artifactId;

    @NotNull
    private final String type;

    @NotBlank
    private final String version;

    @NotEmpty
    private final String classifier;
}
```

Building these two files with `lombok.builder.className=Builder` fails, building them with `lombok.builder.className=*Builder` succeds.

**Expected behavior**
SuperBuilder produces `Artifact.Builder`, `Artifact.BuilderImpl`, `MavenArtifact.Builder` and `MavenArtifact.BuilderImpl` classes.

**Version info (please complete the following information):**
 - Lombok version: 1.18.16
 - javac 11.0.8
 - Apache Maven 3.6.1

### PR DESCRIPTION
**Pull request by janrieke**
`@SuperBuilder` now correctly considers `lombok.builder.className` when generating the `extends` clause for the abstract builder class.
This PR fixes #2647.

### CODE REVIEW

**Comment by janrieke** [comment]
Is there any problem with this PR? I'd be happy to fix it...

File: src/core/lombok/eclipse/handlers/HandleSuperBuilder.java [hunk 1]
```diff
@@ -272,8 +272,9 @@ void setBuilderToAbstract() {
 		};
 		if (extendsClause instanceof QualifiedTypeReference) {
 			QualifiedTypeReference qualifiedTypeReference = (QualifiedTypeReference)extendsClause;
-			String superclassClassName = String.valueOf(qualifiedTypeReference.getLastToken());
-			String superclassBuilderClassName = job.replaceBuilderClassName(superclassClassName);
+			char[] superclassClassName = qualifiedTypeReference.getLastToken();
+			String builderClassNameTemplate = BuilderJob.fixBuilderClassName(annotationNode, "");
```
Comment (Rawi01) [inline src/core/lombok/eclipse/handlers/HandleSuperBuilder.java:276]: Is there any reason you used `""` instead of `null` for the override parameter?

I also think we should rename the `fixBuilderClassName` method, it doesn't fix anything it just returns the current configured builder name. I don't think that this has to be done in this PR.

**Review by Rawi01 — APPROVED** [review]
LGTM

File: src/core/lombok/eclipse/handlers/HandleSuperBuilder.java (hunk 1 above)
Comment (janrieke) [reply src/core/lombok/eclipse/handlers/HandleSuperBuilder.java:276]: I don't know any more, but I probably sort of copied it from line 116.

Comment (janrieke) [reply src/core/lombok/eclipse/handlers/HandleSuperBuilder.java]: Now using `null`instead of an empty string. And I renamed the method anyway. :)

Comment (Rawi01) [reply src/core/lombok/eclipse/handlers/HandleSuperBuilder.java]: Thanks, I think you missed to rename the method in the eclipse handler :smile:

Comment (janrieke) [reply src/core/lombok/eclipse/handlers/HandleSuperBuilder.java]: Next try... ;)

**Review by Rawi01 — APPROVED** [review]
