### PR TITLE
Find ProcessingEnvironment in InteliJ 2020.3 and Kotlin

### LINKED ISSUE #2592: [BUG] Lombok Does not work with IntelliJ EAP 2020.3 Build 203.4203.26
**Describe the bug**
Compiling projects with Lombok in IntelliJ 2020.3 EAP (Build 203.4203.26) leads to:

>java: You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
>  Your processor is: com.sun.proxy.$Proxy32
>  Lombok supports: OpenJDK javac, ECJ

**To Reproduce**
Any project compiled in IntelliJ is affected.

**Version info (please complete the following information):**
 - Lombok version: 1.18.12
 - IntelliJ 2020.3 EAP (Build 203.4203.26)

**Additional context**

IntelliJ is now wrapping the `ProcessingEnvironment` in a `Proxy`. This lead to a problem for us at MapStruct (https://github.com/mapstruct/mapstruct/issues/2215). While trying to fix that and testing with our examples I realized that our examples with Lombok are not compiling anymore.

For us at MapStruct it is quite easy to do this changes, don't know about you at Lombok

Thanks to @bjansen some more information about this:

https://github.com/JetBrains/intellij-community/blob/master/jps/jps-builders-6/src/org/jetbrains/jps/javac/APIWrappers.java

https://github.com/JetBrains/intellij-community/commit/d6f2625c0df5ea7b5be9bad75f5d5c6ecda452d2#commitcomment-42898346

https://youtrack.jetbrains.com/issue/IDEA-250718

Lombok related IntelliJ issue (https://youtrack.jetbrains.com/issue/IDEA-252069)

### PR DESCRIPTION
**Pull request by Rawi01**
This PR fixes #2592. 
I also completed the potential fix for #2412 by @rspilker (he missed to add the additional field to `LombokProcessor`). I don't know why the code to search the processing environment is there at two places, thats why I have not moved it to a different class.

### CODE REVIEW

File: src/core/lombok/core/AnnotationProcessor.java [hunk 1]
```diff
@@ -100,6 +97,40 @@ private static ProcessingEnvironment tryRecursivelyObtainJavacProcessingEnvironm
...
+		}
+	}
+	
+	/**
+	 * InteliJ >= 2020.3
+	 */
+	private static Object tryGetProxyDelegateToField(Class<?> delegateClass, Object instance) {
+		try {
+			InvocationHandler handler = Proxy.getInvocationHandler(instance);
+			return Permit.getField(handler.getClass(), "val$delegateTo").get(handler);
```
Comment (eugenezh) [inline src/core/lombok/core/AnnotationProcessor.java:128]: I would suggest making this heuristic a bit more reliable and not depending on particular field name. Also all Proxy-related suff will remain hidden. 
Consider using the _org.jetbrains.jps.javac.APIWrappers.WrapperDelegateAccessor_ interface.

First, check if the wrapped object is instanceof _APIWrappers.WrapperDelegateAccessor_; 
then use the _APIWrappers.WrapperDelegateAccessor.getWrapperDelegate()_ to access the wrapped object.
I have made the _WrapperDelegateAccessor_ public for this purpose.

Comment (eugenezh) [reply src/core/lombok/core/AnnotationProcessor.java:128]: Similar logic should work for accessing wrapped ProcessingEnvironment too.

Comment (Rawi01) [reply src/core/lombok/core/AnnotationProcessor.java:128]: Thanks for the feedback, I tried to do it that way but it does not work. For compilation I created a stub for `WrapperDelegateAccessor`. At build time the class should be already there but lombok seems to be unable to find it and is unable to perform the cast and the method call.

Comment (eugenezh) [reply src/core/lombok/core/AnnotationProcessor.java:128]: Ah, indeed, this is because JPS classes are deliberately isolated in a separate classloader from annotation processors. This is needed to avoid possible conflicts between libraries that use annotation processors and libraries used by JPS.
Then we can stick with the same idea, but use reflection to access the delegate like this:

Class<?> accessorInterface = Class.forName("org.jetbrains.jps.javac.APIWrappers$WrapperDelegateAccessor", true, proxy.getClass().getClassLoader());
Method accessor = accessorInterface.getMethod("getWrapperDelegate");
Object delegate = accessorInterface.isInstance(proxy)? accessor.invoke(proxy) : null;

The code assumes the "proxy" reference points to the proxy wrapper
